### ISSUE TITLE
LOAD command doesn't work with latest develop ROM

### ISSUE THREAD

**Issue by LRFLEW** [indigodarkwolf/box16#56]
I tested the latest development commit of box16 with the latest development commit of the ROM and found I was getting "File Not Found" errors when trying to load programs in the emulator. To clarify, I'm not using any sort of `-sdcard` argument, so this is an issue with loading from the current directory. I bisected the issue to https://github.com/commanderx16/x16-rom/commit/dd6623727b1fa8468f6a5568f49c3bbde23114f7 (or its parent commit, but I don't think it's that one). I'm guessing that the shifting of functions from moving things to the new bank messed up the function hooking. This isn't an issue with using the latest release ROM, but it's something to keep in mind for the next release.

**Comment by indigodarkwolf** [comment]
Box16 has since been updated with new kernal addresses for various hypercall hooks, and LOAD seems to work fine for me with the current source for Box16 (https://github.com/indigodarkwolf/box16/commit/4871184defd4a01cb28d684ce8cc207b5f099661) and the latest ROM source code (https://github.com/commanderx16/x16-rom/commit/676f4a5744c236eda448cc024c7819f67e8407f9).
