### ISSUE TITLE
16x8 8bpp tiles appear to crash the emulator

### ISSUE THREAD

**Issue by Yazwh0** [indigodarkwolf/box16#60]
Example prg.

No dump file as it wrote a zero byte file.

[Example.zip](https://github.com/indigodarkwolf/box16/files/9862489/Example.zip)

**Comment by indigodarkwolf** [comment]
In the example program there, the first operation is a `jmp ($FFFC)`, which is attempting to jump to the address in $04:$FFFC (bank 4 because it's in the BASIC interpreter). The address happens to be $FFFF, which is what it's setting the program counter to, and that's triggering the emulator's "system crash" logic, which attempts to create a dump file and then exits the emulator entirely.

**Comment by indigodarkwolf** [comment]
So it sounds like removing that instruction fixes the issue? Closing for now, if it turns out I was wrong then feel free to re-open.
